package Cab_Service1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * book.java
 *
 * Created on Jan 9, 2013, 8:04:21 PM
 */


/**
 *
 * @author Hamzah
 */
public class book extends javax.swing.JFrame {

    /** Creates new form book */
    public book() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	this.setTitle("BOOKING");
    	final Object[][] data = new Object[100][8];
        final Object[] Colheads={"regno","type","driver","availibility","Speed","Startplace","reading/day","Maintenance"};
         final DefaultTableModel model = new DefaultTableModel(data,Colheads);
         
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(model);
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        try{   
         	 System.out.println("success1");
          
           
          System.out.println("jjjjjjjjjjjj");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cab_service","root","hamzah"); 
           if (con != null) {
                          System.out.println("A database connection has been established!");
                   }
           
           System.out.println("success2");
           Statement st= con.createStatement();   
           String s1="select * from taxi";  
           System.out.println("success3");
           ResultSet rs=st.executeQuery(s1);  
           int N = model.getRowCount();
           while(N > 0){ model.removeRow(N-1); N--; }
           int i=0; 
           
           while(rs.next()){   
           	System.out.println("success9");
          	 data[i][0]=rs.getInt("regno");
          	System.out.println("success7");
               data[i][1]=rs.getString("Type");  
               
               data[i][2]=rs.getString("Driver"); 
               
               data[i][3]=rs.getString("Availability");
               System.out.println("hiiiiiiiii");
               data[i][4]=rs.getInt("Speed");  
               data[i][5]=rs.getString("Startplace");   
             //  data[i][6]=rs.getInt("Starty");   
               data[i][6]=rs.getInt("readingperday");    
               data[i][7]=rs.getString("maintinance_details");  
               model.addRow(data[i]);
               i++;
              
              }   
          
         
         rs.close();   
         st.close();   
       con.close();   
  }catch(Exception e){   
	   System.out.println("success8");
  } 
  System.out.println("tableeeeee");
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	if(jTextField1.getText()!=null){
                	try{   
              		  Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/cab_service","root","hamzah");   
              	        if (con != null) {
              	                       System.out.println("A database connection has been established!");
              	                  }
              	      System.out.println("success1");
              	    PreparedStatement statement=con.prepareStatement(
                    "INSERT INTO taxi WHERE regno = ?");
              	  System.out.println("success4");
            statement.setString(1, jTextField1.getText()); 
            con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/cab_service", "root",
                    "hamzah");
            Statement st= con.createStatement(); 
           String s1="UPDATE taxi SET Availability= REPLACE( Availability , 'available', 'busy' ) WHERE regno LIKE '"+jTextField1.getText()+"'";
          
           st.executeUpdate(s1);
          // st.executeUpdate(s2);
            st.close();
            con.close();
            System.out.println("success6");
            statement.setString(4, "busy");
            System.out.println("success5");
            statement.executeUpdate();
            System.out.println("success2");
            	
            	
            	
                	}
                	catch(Exception e){
                		e.getMessage();
                		}
                	 jTextField1.setText("");

                   	System.out.println("success3");
                	}
            	 jButton1ActionPerformed(evt);
            	
            }
        });

        jLabel1.setText("Registration Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	this.setVisible(false);
        Admin ad= new Admin();
        ad.setVisible(true); // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new book().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration
}
