import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * customer_details.java
 *
 * Created on Jan 9, 2013, 9:31:02 PM
 */

/**
 *
 * @author Hamzah
 */
public class customer_details extends javax.swing.JFrame {

    /** Creates new form customer_details */
    public customer_details() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	this.setTitle("Customer Details");
    	
    	final Object[][] data = new Object[100][6];
        final Object[] Colheads={"Name","Source","Destination","email_address","Status","Booking id"};
         final DefaultTableModel model = new DefaultTableModel(data,Colheads);
         
         jTable1 = new javax.swing.JTable(model);
        jScrollPane1 = new javax.swing.JScrollPane();
     //   jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        try{   
         //	 System.out.println("success1");
          
           
       //   System.out.println("jjjjjjjjjjjj");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cab_service","root","hamzah"); 
           if (con != null) {
                         // System.out.println("A database connection has been established!");
                   }
           
         //  System.out.println("success2");
           Statement st= con.createStatement();   
           String s1="select * from customer";  
           //System.out.println("success3");
           ResultSet rs=st.executeQuery(s1);  
           int N = model.getRowCount();
           while(N > 0){ model.removeRow(N-1); N--; }
           int i=0; 
          // System.out.println("success3");
           while(rs.next()){   
       //    	System.out.println("success9");
          	 data[i][0]=rs.getString("Name");
          	//System.out.println("success7");
               data[i][1]=rs.getString("Source");  
               
               data[i][2]=rs.getString("Destination"); 
               
               data[i][3]=rs.getString("Address");
              // System.out.println("hiiiiiiiii");
               data[i][4]=rs.getString("status");  
               data[i][5]=rs.getString("booking_id");   
             //  data[i][6]=rs.getString("taxino");
               model.addRow(data[i]);
               i++;
              
              }   
          
         
         rs.close();   
         st.close();   
       con.close();   
  }catch(Exception e){   
	   System.out.println("success8");
  } 
 // System.out.println("tableeeeee");
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Delete customer of name:");

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
             
            	if(jTextField1.getText()!=null){
                	try{   
              		  Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/cab_service","root","hamzah");   
              	        if (con != null) {
              	                      // System.out.println("A database connection has been established!");
              	                  }
              	     // System.out.println("success1");
              	        PreparedStatement statement=con.prepareStatement(
                                  "DELETE FROM customer WHERE Name = ?");
                          statement.setString(1, jTextField1.getText()); 
                          statement.executeUpdate();
                       //   System.out.println("success22");
                             }catch(Exception e){   
                      e.getMessage();   
                  }   
              	 jTextField1.setText("");

           //   	System.out.println("success3");
            
              	}
            	
            	int N = model.getRowCount();
                while(N > 0){ model.removeRow(N-1); N--; }
                  try{   
                 //	 System.out.println("success1");
                 Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/cab_service","root","hamzah");   
                 if (con != null) {
                         //       System.out.println("A database connection has been established!");
                           }
               //  System.out.println("success2");
                      Statement st= con.createStatement();   
                      String s1="select * from customer";   
                      ResultSet rs=st.executeQuery(s1); 
                      int i=0;
                      while(rs.next()){   
                    	  data[i][0]=rs.getString("Name");
                        //	System.out.println("success7");
                             data[i][1]=rs.getString("Source");  
                             
                             data[i][2]=rs.getString("Destination"); 
                             
                             data[i][3]=rs.getString("Address");
                       //      System.out.println("hiiiiiiiii");
                             data[i][4]=rs.getString("status");  
                             data[i][5]=rs.getString("booking_id");  
                             model.addRow(data[i]);
                             i++;
                        
                         }  
                       jScrollPane1.setViewportView(jTable1);
                      jScrollPane1.repaint();
                 //    System.out.println("complete");
                    rs.close();   
                    st.close();   
                  con.close();   
            }catch(Exception e){   
                e.getMessage();   
            } 
       
            	 jTextField1.setText("");
            	
            	
            	
            	
            	
            	
            	
            	
            	
            	jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
            	
            	
            	
            	

                 
            
            	
            	
            	
            	
            	
            	
            jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(264, 264, 264))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	this.setVisible(false);
        Admin ad= new Admin();
        ad.setVisible(true);  // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new customer_details().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration
}
