/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * taxi_detail.java
 *
 * Created on Jan 7, 2013, 10:50:23 PM
 */

import java.util.*;   
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;  

import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hamzah
 */
public class taxi_details extends javax.swing.JFrame {

    /** Creates new form taxi_detail */
    public taxi_details() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    		this.setTitle("Taxi Details");
    	
    	final Object[][] data = new Object[100][8];
        final Object[] Colheads={"regno","type","driver","Availibility","Speed","Start Place","reading/day","Maintenance"};
         final DefaultTableModel model = new DefaultTableModel(data,Colheads);
         
         jTable1 = new javax.swing.JTable(model);
         jButton1 = new javax.swing.JButton();
         jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      
        try{   
          	 System.out.println("success1");
           
            
           System.out.println("jjjjjjjjjjjj");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cab_service","root","hamzah"); 
            if (con != null) {
                           System.out.println("A database connection has been established!");
                    }
            
            System.out.println("success2");
            Statement st= con.createStatement();   
            String s1="select * from taxi";  
            System.out.println("success3");
            ResultSet rs=st.executeQuery(s1);  
            int N = model.getRowCount();
            while(N > 0){ model.removeRow(N-1); N--; }
            int i=0; 
            
            while(rs.next()){   
            	System.out.println("success9");
           	 data[i][0]=rs.getString("regno");
           	System.out.println("success7");
                data[i][1]=rs.getString("Type");  
                
                data[i][2]=rs.getString("Driver"); 
                
                data[i][3]=rs.getString("Availability");
                System.out.println("hiiiiiiiii");
                data[i][4]=rs.getInt("Speed");  
                data[i][5]=rs.getString("Startplace");   
               // data[i][6]=rs.getInt("Starty");   
                data[i][6]=rs.getInt("readingperday");    
                data[i][7]=rs.getString("maintinance_details");  
                model.addRow(data[i]);
                i++;
               
               }   
           
          
          rs.close();   
          st.close();   
        con.close();   
   }catch(Exception e){   
	   System.out.println("success8");
   } 
   System.out.println("tableeeeee");
   jScrollPane1.setViewportView(jTable1);
        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

       

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(746, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
      this.setVisible(false);
      Admin ad= new Admin();
      ad.setVisible(true);// TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taxi_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taxi_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taxi_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taxi_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        System.out.println("success9");
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new taxi_details().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration
}
